### ISSUE TITLE
php 7.1.8 with zend-validator 2.10.0 : undefined constant INTL_IDNA_VARIANT_UTS46

### ISSUE THREAD

**Issue by samsonasik** [zendframework/zend-validator#193] opened 2017-08-19 14:15 UTC
in EmailAddress.php: 557

https://github.com/zendframework/zend-validator/blob/33caf7f7ab2cc3181895820b2fe17bd792f72226/src/EmailAddress.php#L556-L558

Need to check if constant available ?

**Comment by xtreamwayz** [comment] 2017-08-19 14:57
Duplicate of #192

**Comment by xtreamwayz** [comment] 2017-08-19 15:15
In addition to my explanation there: If more people experience this, I think a check might be needed. Although I'm concerned about the state of their server OS if they depend on system libraries from before 2012.

**Comment by samsonasik** [comment] 2017-08-19 15:37
@xtreamwayz I've created PR #194 for its check

**Comment by ArtemChornovol** [comment] 2017-08-22 09:53
We use Amazon, and the latest version of ICU library, (in accordance with #192) But it does not work!

Version: 50.1.2
Release Date: 2012-12-17
API Changes since ICU4C 49
Readme
This is a maintenance release affecting only the Layout Engine ABI. It only incorporates bug #9826 which fixes a regression in ICU4C 50.1.1.
Users not using the Layout Engine may remain on ICU4C 50.1.1 (see below for 50.1.1 changes)

**Comment by samsonasik** [comment] 2017-08-22 10:07
@ArtemChornovol for workaround, downgrade set in composer `"zendframework/zend-validator": "~2.9.2"` is the way while waiting for #194 going to be merged or any other solution found for it.

**Closed** 2017-08-22 14:21 UTC
