### ISSUE TITLE
Wrong documentation for "pre-translated validation messages"

### ISSUE THREAD

**Issue by buschn** [zendframework/zend-validator#182] opened 2017-07-20 09:21 UTC
The documentation on https://zendframework.github.io/zend-validator/messages/ for "Using pre-translated validation messages" seems to be wrong. For new Zend\Mvc\I18n\Translator() no parameter is given, but the class requires exactly one parameter.

**Comment by froschdesign** [comment] 2017-07-20 10:16
Duplicate of #106

**Closed by froschdesign** 2017-07-20 10:16 UTC
